const REPORT_ACTION = {
  FETCH_CHART_DATA_DAY: "FETCH_CHART_DATA_DAY",
  FETCH_CHART_DATA_MONTH: "FETCH_CHART_DATA_MONTH",
  FETCH_CHART_DATA_YEAR: "FETCH_CHART_DATA_YEAR",

  INCRE_PAGE_INDEX_DAY: "INCRE_PAGE_INDEX_DAY",
  INCRE_PAGE_INDEX_MONTH: "INCRE_PAGE_INDEX_MONTH",
  INCRE_PAGE_INDEX_YEAR: "INCRE_PAGE_INDEX_YEAR",

  REDUCE_PAGE_INDEX_DAY: "REDUCE_PAGE_INDEX_DAY",
  REDUCE_PAGE_INDEX_MONTH: "REDUCE_PAGE_INDEX_MONTH",
  REDUCE_PAGE_INDEX_YEAR: "REDUCE_PAGE_INDEX_YEAR",

  UPDATE_SUMMARY_DAY: "UPDATE_SUMMARY_DAY",
  UPDATE_SUMMARY_MONTH: "UPDATE_SUMMARY_MONTH",
  UPDATE_SUMMARY_YEAR: "UPDATE_SUMMARY_YEAR",

  UPDATE_ACTIVE_INDEX_DAY: "UPDATE_ACTIVE_INDEX_DAY",
  UPDATE_ACTIVE_INDEX_MONTH: "UPDATE_ACTIVE_INDEX_MONTH",
  UPDATE_ACTIVE_INDEX_YEAR: "UPDATE_ACTIVE_INDEX_YEAR",

  UPDATE_DAILY_YEAR: "UPDATE_DAILY_YEAR",
  UPDATE_DAILY_MONTH: "UPDATE_DAILY_MONTH",

  UPDATE_MONTHLY_YEAR: "UpDATE_MONTHLY_YEAR"  
}

export {REPORT_ACTION}