const STORAGE_ACTION = {
  BOOKING_LIST: "booking_list",
  CONFIRM_LIST: "confirm_list",
  COMPLETE_LIST: "complete_list",

  BOOKING_TO_CONFIRM: "BOOKING_TO_CONFIRM",

  PRICING_LIST: "PRICING_LIST",
  STORAGE_TAB: "STORAGE_TAB",
  IS_LOAD_DONE: "IS_LOAD_DONE",
}

export {STORAGE_ACTION}