const config = {
    "Serial": "serial",
    "TypeTrip": "type_trip",
    "Status": "status",
    "Name_customer": "name_customer",
    "EmailGuest": "email",
    "PhoneNumber": "phone_number",
    "Vehicle_type": "vehicle_type",
    "Price": "price",
    "System_price": "system_price",
    "Price_vn": "price_vn",
    "HomeName": "name_leave",
    "NameArrive": "name_arrive",
    "Id_trip": "id_trip",
    "TimeBook": "time_book",
    "TimeLeave": "time_leave",
    "TimeAccept": "time_accept",
    "TimeCancel": "time_cancel",
    "TimeComplete": "time_complete",
    "note": "note",
    "FlightCode": "flight_code",
    "Price_host": "price_salepoint",
    "Extra_price_host": "extra_price_salepoint",
    "Price_supplier": "extra_price_supplier",
    "Note_host": "note_of_salepoint",
    "Note_supplier": "note_of_supplier"
};
export {config};